### ISSUE TITLE
joplin.search() and query with '/search/' endpoint not working

### ISSUE THREAD

**Issue by alpayne** [foxmask/joplin-api#15]
Calling `joplin.search("search_string")` results in:

_words[0] = query
IndexError: list assignment index out of range_

_words_ is still empty at this point, so a value can't be directly assigned _words[0]_ yet.

If I instead try to query directly with the search endpoint using `joplin.query('get','/search/',"search_string")`, it returns:

_Bad Request for url: http://127.0.0.1:41184/search/?token=...&fields=search_string_

The _/search/_ endpoint needs a "query" parameter instead of "fields".

**Comment by foxmask** [comment]
Hi,
I'll have a look at it at it seems the code of the API is not sync with last specification.

I paste the spec of today march 27th

---
## Searching

Call GET /search?query=YOUR_QUERY to search for notes. This end-point supports the field parameter which is recommended to use so that you only get the data that you need. The query syntax is as described in the main documentation: https://joplinapp.org/#searching

To retrieve non-notes items, such as notebooks or tags, add a type parameter and set it to the required item type name. In that case, full text search will not be used - instead it will be a simple case-insensitive search. You can also use * as a wildcard. This is convenient for example to retrieve notebooks or tags by title.

For example, to retrieve the notebook named recipes: GET /search?query=recipes&type=folder

To retrieve all the tags that start with project-: GET /search?query=project-*&type=tag
Item type IDs

## Item type IDs 
might be refered to in certain object you will retrieve from the API. This is the correspondance between name and ID:

Name | Value
-- | --
note | 1
folder | 2
setting | 3
resource | 4
tag | 5
note_tag | 6
search | 7
alarm | 8
master_key | 9
item_change | 10
note_resource | 11
resource_local_state | 12
revision | 13
migration | 14
smart_filter | 15
